<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VcpkgInstalledDir Condition="'$(VcpkgInstalledDir)' == ''">$(MSBuildThisFileDirectory)vcpkg_installed\</VcpkgInstalledDir>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Platform)' == 'Win32'">
    <ClCompile>
      <AdditionalIncludeDirectories>$(VcpkgInstalledDir)x86-windows\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(VcpkgInstalledDir)x86-windows\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies Condition="'$(MSBuildProjectName)' == 'imobiledevice'">libssl.lib;libcrypto.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(MSBuildProjectName)' == 'AltServer'">libssl.lib;libcrypto.lib;zlib.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
